pimcore_data_hub:
    configurations:
        frequenciesImport:
            general:
                active: true
                type: dataImporterDataObject
                name: frequenciesImport
                description: ''
                group: ''
                path: null
                modificationDate: 1699888681
                createDate: 1699570438
            loaderConfig:
                type: upload
                settings:
                    uploadFilePath: frequenciesImport/upload.import
            interpreterConfig:
                type: csv
                settings:
                    skipFirstRow: true
                    delimiter: ','
                    enclosure: '"'
                    escape: \
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: '3'
                loadingStrategy:
                    type: attribute
                    settings:
                        dataSourceIndex: '0'
                        attributeName: frequenciesID
                        language: ''
                        includeUnpublished: true
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /Frequencies
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: noChangeUnpublishNew
            processingConfig:
                executionType: sequential
                idDataIndex: '0'
                doDeltaCheck: true
                cleanup:
                    strategy: delete
            mappingConfig:
                -
                    label: '0'
                    dataSourceIndex:
                        - '0'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: frequenciesID
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: '1'
                    dataSourceIndex:
                        - '1'
                    settings:
                        loadStrategy: attribute
                        attributeDataObjectClassId: '1'
                        attributeName: airId
                        partialMatch: 'on'
                        attributeLanguage: ''
                        loadUnpublished: 'on'
                    transformationResultType: dataObjectArray
                    dataTarget:
                        type: manyToManyRelation
                        settings:
                            fieldName: airportRef
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                            overwriteMode: replace
                    transformationPipeline:
                        -
                            type: asArray
                        -
                            settings:
                                loadStrategy: attribute
                                attributeDataObjectClassId: '1'
                                attributeName: airId
                                partialMatch: 'on'
                                attributeLanguage: ''
                                loadUnpublished: 'on'
                            type: loadDataObject
                -
                    label: '5'
                    dataSourceIndex:
                        - '5'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: mhz
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: '2'
                    dataSourceIndex:
                        - '2'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: airportIdent
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: '3'
                    dataSourceIndex:
                        - '3'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: frequenciesType
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: '4'
                    dataSourceIndex:
                        - '4'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: description
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
            executionConfig:
                scheduleType: recurring
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
